# IMPORTANT! This docker file is DOES NOT have sharding & replication across 3+ nodes set up.
# We'll probably need to do the set up manually & export custom Docker images

services:
  node_1:
    container_name: node_1
    image: mongo
    ports:
      - 30001:27020
    networks:
      - default
    volumes:
      - ./db/node1:/db
      - ./scripts:/home/scripts
    entrypoint: ["/home/scripts/init-node.sh", "1"]

  node_2:
    container_name: node_2
    image: mongo
    networks:
      - default
    volumes:
      - ./db/node2:/db
      - ./scripts:/home/scripts
    entrypoint: ["/home/scripts/init-node.sh", "2"]

  node_3:
    container_name: node_3
    image: mongo
    networks:
      - default
    volumes:
      - ./db/node3:/db
      - ./scripts:/home/scripts
    entrypoint: ["/home/scripts/init-node.sh", "3"]

networks:
  default:
    name: team-nosequel

volumes:
  scripts:
