# IMPORTANT! This docker file is DOES NOT have sharding & replication across 3+ nodes set up.
# We'll probably need to do the set up manually & export custom Docker images

services:
  node_1:
    image: mongo
    ports:
      - 30001:27017
  node_2:
    image: mongo
    ports:
      - 30002:27017
  node_3:
    image: mongo
    ports:
      - 30003:27017
